base_url = "https://nxm.rs/"
title = "Nexum"
description = "Everything, blazing fast and decentralised"
build_search_index = true
generate_feeds = true
compile_sass = true
minify_html = true
taxonomies = [{ name = "tags" }]

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[markdown]
highlight_code = true
highlight_theme = "ayu-light"

[extra]
toc = true
use_cdn = false
favicon = "/icon/favicon.png"
theme = "toggle"              # light, dark, auto, toggle
fancy_code = true
dynamic_note = true           # a note that can be toggled
mathjax = true
mathjax_dollar_inline_enable = true
repo_url = "https://github.com/nullisxyz/website-nexum/tree/main/content/"

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    # { name = "/projects", url = "/projects", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
    { name = "/tags", url = "/tags", weight = 4 },
]

socials = [
    { name = "twitter", url = "https://x.com/nxm_rs", icon = "twitter" },
    { name = "github", url = "https://github.com/nxm-rs", icon = "github" },
]

[extra.analytics]
enabled = true

[extra.analytics.plausible]
domain = "nxm.rs"
script_url = "https://plausible.nxm.rs/js/script.hash.outbound-links.pageview-props.tagged-events.js"
